### ISSUE TITLE
Linting fails

### ISSUE THREAD

**Issue by mnemanja** [vasanthk/react-es6-webpack-boilerplate#16]
After running the `npm run lint` I get this error:

```
C:\www\React2Do>npm run lint

> react-es6-webpack-boilerplate@4.0.0 lint C:\www\React2Do
> eslint .

C:\www\React2Do\node_modules\eslint-plugin-react\lib\rules\prop-types.js:450
          propTypes.parent.type !== 'AssignmentExpression' &&
                          ^

TypeError: Cannot read property 'type' of undefined
    at markPropTypesAsDeclared (C:\www\React2Do\node_modules\eslint-plugin-react\lib\rules\prop-types.js:450:27)
    at C:\www\React2Do\node_modules\eslint-plugin-react\lib\rules\prop-types.js:572:9
    at Array.forEach (native)
    at EventEmitter.ObjectExpression (C:\www\React2Do\node_modules\eslint-plugin-react\lib\rules\prop-types.js:568:23)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at Controller.controller.traverse.enter (C:\www\React2Do\node_modules\eslint\lib\eslint.js:725:25)
    at Controller.__execute (C:\www\React2Do\node_modules\estraverse\estraverse.js:393:31)
    at Controller.traverse (C:\www\React2Do\node_modules\estraverse\estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (C:\www\React2Do\node_modules\eslint\lib\eslint.js:718:24)

```

**Comment by amilajack** [comment]
Made a PR that fixes this. Try again when its merged: https://github.com/vasanthk/react-es6-webpack-boilerplate/pull/23
